### ISSUE TITLE
📦 Feature Tracking

### ISSUE THREAD

**Issue by nazhard** [nazhard/gigit#1]
I know it's just a hobby project, but I have 24 hours of time and instead of doing bad things, it's better to make something nyaan nyaan!

...And perhaps you'd like to help me too? UwU with pleasure senpai!

### default
- [x] gigit nazhard/do

### specific branch, commit hash, tag
- [ ] gigit user/repo#dev
- [x] gigit user/repo#d92kDmA
- [ ] gigit user/repo#v0.1.0

### sub directory. Useful when download template
- [ ] gigit user/repo/dir
- [ ] gigit github:user/repo/dir

### specific host name
- [ ] gigit github:user/repo
- [ ] gigit gitlab:user/repo
